version: '3.8'

services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    container_name: jupyter_pyspark
    restart: no
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
      - 4040-4080:4040-4080
