version: "3.8"

services:
  pyspark-notebook:
    container_name: pyspark_container
    image: jupyter/pyspark-notebook
    restart: no
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
      - 4040-4080:4040-4080
