version: '3.8'

services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    container_name: jupyter_python
    restart: no
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
