version: '3.8'

services:
  julia-notebook:
    image: jupyter/julia-notebook
    container_name: julia_notebook
    restart: no
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
