version: '3.8'

services:
  miniconda3:
    container_name: miniconda3_python
    image: continuumio/miniconda3
    working_dir: /opt/notebooks
    volumes:
      - .:/opt/notebooks
    ports:
      - 8888:8888
    command: >
      bash -c "
      conda install -y jupyter &&
      jupyter notebook
      --notebook-dir=/opt/notebooks
      --ip='*'
      --port=8888
      --no-browser
      --allow-root
      "
